name: TEST Feature Request (e.g. New Functionality)
description: test
title: I Think [this cool thing] Would be a Great Addition to the Application
labels: ["enhancement", "feature request"]
assignees:
  - marshallrobinson
body:
  - type: textarea
    id: requestReason
    attributes:
        label: Why do you feel this application needs what you're requesting?
        placeholder: A clear and concise description of what you feel the problem is. Ex. I'm always frustrated when [...]
    validations:
        required: true
  - type: textarea
    id: solution
    attributes:
        label: Describe the solution you'd like and why it builds value
        placeholder: A clear and concise description of what you want to happen and what value it will bring. Ex. This will make my life better because [...]. Feel free to attach screenshots or anything you think would help show what you're describing.
    validations:
        required: true
  - type: textarea
    id: audienceImpact
    attributes:
        label: What impact will this new functionality have on this application's audience?
        placeholder: A clear and concise description of how this will positively impact a broad audience of users.
    validations:
        required: true
  - type: dropdown
    id: urgency
    attributes:
        label: How Urgent is this?
        options:
          - Low
          - Medium
          - High
    validations:
        required: true
  - type: textarea
    id: moreEvidence
    attributes:
        label: Please provide additional evidence from other users to support medium and high ranking
        placeholder: Attach emails, user-feedback, etc. showing evidence that this new feature would have a positive impact.
    validations:
        required: false
  - type: markdown
    attributes:
        value: "### **All feature requests will be reviewed for future applciation releases**"
